package com.ke.ticketsystemke.entity;

public enum AccessKey {
    VIEW_DASHBOARD,

    VIEW_TICKETS,
    CREATE_TICKET,
    PICK_TICKET,
    ASSIGN_TICKET,
    START_WORK,
    COMPLETE_TICKET,
    CANCEL_TICKET,
    UPDATE_WARRANTY,
    VIEW_WARRANTY,
    MANAGE_WARRANTY,

    VIEW_CUSTOMER_HISTORY,

    VIEW_CHARGES,
    ADD_CHARGE,
    DELETE_CHARGE,

    USE_TICKET_SEARCH,
    USE_TICKET_FILTERS,
    USE_SMART_SUGGESTIONS,

    VIEW_EMPLOYEE_MANAGEMENT,
    MANAGE_EMPLOYEES,

    VIEW_ROLE_MANAGEMENT,
    MANAGE_ROLES,

    APPROVE_DEVICE_PAIRING,

    VIEW_TICKET_CATEGORY_MANAGEMENT,
    MANAGE_TICKET_CATEGORIES,

    VIEW_TICKET_FIELD_MANAGEMENT,
    MANAGE_TICKET_FIELDS,

    VIEW_CATEGORY_FIELD_CONFIGURATION,
    MANAGE_CATEGORY_FIELD_CONFIGS,

    VIEW_DROPDOWN_SOURCE_MANAGEMENT,
    MANAGE_DROPDOWN_SOURCES
}
