package com.ke.ticketsystemke.entity;

public enum WarrantyClaimState {
    DETAILS_REQUIRED, COMPLAINT_REQUIRED, COMPLAINT_REGISTRATION_PENDING,
    VISIT_SCHEDULING_REQUIRED, VISIT_PENDING, VISIT_COMPLETED_AWAITING_RESULT, AWAITING_RESULT,
    MANUFACTURER_REPAIR_COMPLETED, REPLACEMENT_APPROVED_AWAITING_PRODUCT,
    WARRANTY_REJECTED_AWAITING_DECISION, CUSTOMER_DECISION_PENDING,
    REPLACEMENT_RECEIVED, RESOLVED, DELIVERY_PENDING, CLOSED
}
