package com.ke.ticketsystemke.entity;
import jakarta.persistence.*;import java.time.Instant;
@Entity @Table(name="warranty_attachments")
public class WarrantyAttachment{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)private Long id;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="warranty_claim_id",nullable=false)private WarrantyClaim warrantyClaim;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="warranty_replacement_id")private WarrantyReplacement warrantyReplacement;@Enumerated(EnumType.STRING)@Column(nullable=false,length=60)private WarrantyAttachmentCategory category;
 @Column(nullable=false,length=255)private String originalFilename;@Column(nullable=false,length=255)private String displayFilename;@Column(nullable=false,length=30)private String storageProvider;@Column(nullable=false,unique=true,length=180)private String storageKey;@Column(nullable=false,length=80)private String detectedMimeType;@Column(nullable=false)private long sizeBytes;@Column(nullable=false,length=64)private String checksum;private Integer imageWidth;private Integer imageHeight;@Column(nullable=false)private boolean active=true;private Long supersededByAttachmentId;
 @Column(nullable=false,updatable=false)private Instant uploadedAt;@Column(nullable=false,updatable=false,length=80)private String uploadedByEmployeeId;@Column(length=120)private String uploadedByEmployeeName;private Instant deactivatedAt;@Column(length=80)private String deactivatedByEmployeeId;@Column(length=1000)private String deactivationReason;@Column(nullable=false,updatable=false)private Instant createdAt;@Column(nullable=false)private Instant updatedAt;@Version@Column(nullable=false)private Long version;
 @PrePersist void create(){Instant n=Instant.now();if(uploadedAt==null)uploadedAt=n;if(createdAt==null)createdAt=n;updatedAt=n;}@PreUpdate void update(){updatedAt=Instant.now();}
 public Long getId(){return id;}public WarrantyClaim getWarrantyClaim(){return warrantyClaim;}public void setWarrantyClaim(WarrantyClaim v){warrantyClaim=v;}public WarrantyReplacement getWarrantyReplacement(){return warrantyReplacement;}public void setWarrantyReplacement(WarrantyReplacement v){warrantyReplacement=v;}public WarrantyAttachmentCategory getCategory(){return category;}public void setCategory(WarrantyAttachmentCategory v){category=v;}public String getOriginalFilename(){return originalFilename;}public void setOriginalFilename(String v){originalFilename=v;}public String getDisplayFilename(){return displayFilename;}public void setDisplayFilename(String v){displayFilename=v;}public String getStorageProvider(){return storageProvider;}public void setStorageProvider(String v){storageProvider=v;}public String getStorageKey(){return storageKey;}public void setStorageKey(String v){storageKey=v;}public String getDetectedMimeType(){return detectedMimeType;}public void setDetectedMimeType(String v){detectedMimeType=v;}public long getSizeBytes(){return sizeBytes;}public void setSizeBytes(long v){sizeBytes=v;}public String getChecksum(){return checksum;}public void setChecksum(String v){checksum=v;}public Integer getImageWidth(){return imageWidth;}public void setImageWidth(Integer v){imageWidth=v;}public Integer getImageHeight(){return imageHeight;}public void setImageHeight(Integer v){imageHeight=v;}public boolean isActive(){return active;}public void setActive(boolean v){active=v;}public Long getSupersededByAttachmentId(){return supersededByAttachmentId;}public void setSupersededByAttachmentId(Long v){supersededByAttachmentId=v;}public Instant getUploadedAt(){return uploadedAt;}public String getUploadedByEmployeeId(){return uploadedByEmployeeId;}public void setUploadedByEmployeeId(String v){uploadedByEmployeeId=v;}public String getUploadedByEmployeeName(){return uploadedByEmployeeName;}public void setUploadedByEmployeeName(String v){uploadedByEmployeeName=v;}public Instant getDeactivatedAt(){return deactivatedAt;}public void setDeactivatedAt(Instant v){deactivatedAt=v;}public String getDeactivatedByEmployeeId(){return deactivatedByEmployeeId;}public void setDeactivatedByEmployeeId(String v){deactivatedByEmployeeId=v;}public String getDeactivationReason(){return deactivationReason;}public void setDeactivationReason(String v){deactivationReason=v;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}public Long getVersion(){return version;}
}
