package com.ke.ticketsystemke.entity;
public enum WarrantyVisitOutcome { INSPECTION_COMPLETED, REPAIR_ATTEMPTED, PART_REQUIRED, PRODUCT_TAKEN_TO_SERVICE_CENTER, FOLLOW_UP_REQUIRED, NO_ACTION_TAKEN, ENGINEER_DID_NOT_VISIT, OTHER }
