package com.ke.ticketsystemke.entity;

public enum WarrantyClaimEventType {
    WARRANTY_CLAIM_CREATED, WARRANTY_DETAILS_UPDATED, WARRANTY_OWNER_CHANGED,
    WARRANTY_STATE_CHANGED, WARRANTY_CLAIM_CLOSED,
    WARRANTY_COMPLAINT_REGISTRATION_PENDING, WARRANTY_COMPLAINT_REGISTERED,
    WARRANTY_VISIT_SCHEDULED, WARRANTY_EXPECTED_VISIT_UPDATED, WARRANTY_VISIT_RECORDED,
    WARRANTY_FOLLOW_UP_SCHEDULED, WARRANTY_FOLLOW_UP_UPDATED, WARRANTY_FOLLOW_UP_CLEARED
}
