package com.ke.ticketsystemke.entity;

public enum WarrantyClaimEventType {
    WARRANTY_CLAIM_CREATED, WARRANTY_DETAILS_UPDATED, WARRANTY_OWNER_CHANGED,
    WARRANTY_STATE_CHANGED, WARRANTY_CLAIM_CLOSED,
    WARRANTY_COMPLAINT_REGISTRATION_PENDING, WARRANTY_COMPLAINT_REGISTERED,
    WARRANTY_VISIT_SCHEDULED, WARRANTY_EXPECTED_VISIT_UPDATED, WARRANTY_VISIT_RECORDED,
    WARRANTY_FOLLOW_UP_SCHEDULED, WARRANTY_FOLLOW_UP_UPDATED, WARRANTY_FOLLOW_UP_CLEARED,
    WARRANTY_MANUFACTURER_REPAIR_COMPLETED, WARRANTY_REJECTED, WARRANTY_REJECTION_DECISION_RECORDED,
    WARRANTY_CUSTOMER_DID_NOT_PROCEED, WARRANTY_REPLACEMENT_APPROVED, WARRANTY_MOVED_TO_READY_DELIVERY,
    WARRANTY_REPLACEMENT_RECEIVED, WARRANTY_REPLACEMENT_DETAILS_UPDATED, WARRANTY_REPLACEMENT_SUPERSEDED,
    WARRANTY_REPLACEMENT_READY_FOR_DELIVERY, WARRANTY_REPLACEMENT_GIVEN_TO_CUSTOMER, WARRANTY_REPLACEMENT_CLAIM_CLOSED,
    WARRANTY_CONTINUED_AS_PAID_REPAIR
}
