package com.ke.ticketsystemke.entity;

public enum WarrantyClaimState {
    DETAILS_REQUIRED, COMPLAINT_REQUIRED, COMPLAINT_REGISTRATION_PENDING,
    VISIT_SCHEDULING_REQUIRED, VISIT_PENDING, VISIT_COMPLETED_AWAITING_RESULT, AWAITING_RESULT,
    RESOLVED, DELIVERY_PENDING, CLOSED
}
