package com.ke.ticketsystemke.storage;
import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Component;import java.io.*;import java.nio.file.*;import java.security.*;import java.util.*;
@Component
public class FilesystemWarrantyFileStorage implements WarrantyFileStorage{
 private final Path root;private final boolean enabled;
 public FilesystemWarrantyFileStorage(@Value("${warranty.files.enabled:${WARRANTY_FILE_STORAGE_ENABLED:false}}")boolean enabled,@Value("${warranty.files.root:${WARRANTY_FILE_STORAGE_ROOT:}}")String configured){this.enabled=enabled;if(enabled&&(configured==null||configured.isBlank()))throw new IllegalStateException("WARRANTY_FILE_STORAGE_ROOT is required when warranty file storage is enabled");root=configured==null||configured.isBlank()?Path.of(System.getProperty("java.io.tmpdir"),"ke-warranty-disabled"):Path.of(configured).toAbsolutePath().normalize();}
 public StoredFile store(Long claimId,InputStream input)throws IOException{requireEnabled();Path staging=root.resolve(".staging");Files.createDirectories(staging);Path temp=Files.createTempFile(staging,"upload-",".part");MessageDigest digest=sha256();long size=0;try(InputStream in=input;OutputStream out=Files.newOutputStream(temp)){byte[] b=new byte[8192];for(int n;(n=in.read(b))>=0;){out.write(b,0,n);digest.update(b,0,n);size+=n;}}catch(Exception e){Files.deleteIfExists(temp);throw e;}String name=UUID.randomUUID().toString();String key="claims/"+claimId+"/"+name;Path target=safe(key);Files.createDirectories(target.getParent());try{Files.move(temp,target,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temp,target);}return new StoredFile(key,size,HexFormat.of().formatHex(digest.digest()));}
 public InputStream open(String key)throws IOException{return Files.newInputStream(safe(key),StandardOpenOption.READ);}public void deletePermanent(String key)throws IOException{Files.deleteIfExists(safe(key));}public boolean exists(String key){return Files.isRegularFile(safe(key));}public Path resolvedPath(String key){return safe(key);}private Path safe(String key){Path p=root.resolve(key).normalize();if(!p.startsWith(root))throw new IllegalArgumentException("Invalid storage key");return p;}private void requireEnabled(){if(!enabled)throw new IllegalStateException("Warranty file storage is disabled");}private MessageDigest sha256(){try{return MessageDigest.getInstance("SHA-256");}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
