package com.ke.ticketsystemke.controller;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.service.WarrantyClaimService; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/volt/tickets/{ticketId}/warranty")
public class WarrantyClaimController {
 private final WarrantyClaimService service; private final com.ke.ticketsystemke.service.WarrantyActionService actions; public WarrantyClaimController(WarrantyClaimService service,com.ke.ticketsystemke.service.WarrantyActionService actions){this.service=service;this.actions=actions;}
 @GetMapping public ResponseEntity<WarrantyClaimResponse> get(@PathVariable Long ticketId,Authentication auth){WarrantyClaimResponse response=service.get(ticketId,auth.getName());return response==null?ResponseEntity.noContent().build():ResponseEntity.ok(response);}
 @PostMapping public ResponseEntity<WarrantyClaimResponse> create(@PathVariable Long ticketId,@Valid @RequestBody(required=false) CreateWarrantyClaimRequest request,Authentication auth){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(ticketId,request==null?new CreateWarrantyClaimRequest():request,auth.getName()));}
 @PatchMapping("/{claimId}") public WarrantyClaimResponse update(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody UpdateWarrantyClaimRequest request,Authentication auth){return service.update(ticketId,claimId,request,auth.getName());}
 @GetMapping("/{claimId}/events") public WarrantyClaimEventPageResponse events(@PathVariable Long ticketId,@PathVariable Long claimId,@RequestParam(required=false) Integer page,@RequestParam(required=false) Integer size,Authentication auth){return service.history(ticketId,claimId,page,size,auth.getName());}
 @PostMapping("/{claimId}/actions/complaint-registration-pending") public WarrantyClaimResponse complaintPending(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody MarkComplaintRegistrationPendingRequest request,Authentication auth){return actions.markComplaintPending(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/register-complaint") public WarrantyClaimResponse registerComplaint(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody RegisterWarrantyComplaintRequest request,Authentication auth){return actions.registerComplaint(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/schedule-visit") public WarrantyClaimResponse scheduleVisit(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody ScheduleWarrantyVisitRequest request,Authentication auth){return actions.scheduleVisit(ticketId,claimId,request,auth.getName());}
 @PatchMapping("/{claimId}/visit") public WarrantyClaimResponse updateVisit(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody UpdateExpectedWarrantyVisitRequest request,Authentication auth){return actions.updateExpectedVisit(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/record-visit") public WarrantyClaimResponse recordVisit(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody RecordWarrantyVisitRequest request,Authentication auth){return actions.recordVisit(ticketId,claimId,request,auth.getName());}
 @PutMapping("/{claimId}/follow-up") public WarrantyClaimResponse followUp(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody UpdateWarrantyFollowUpRequest request,Authentication auth){return actions.updateFollowUp(ticketId,claimId,request,auth.getName());}
}
