package com.ke.ticketsystemke.controller;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.service.WarrantyClaimService; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/volt/tickets/{ticketId}/warranty")
public class WarrantyClaimController {
 private final WarrantyClaimService service; private final com.ke.ticketsystemke.service.WarrantyActionService actions; private final com.ke.ticketsystemke.service.WarrantyResolutionService resolutions; private final com.ke.ticketsystemke.service.WarrantyReplacementService replacements; public WarrantyClaimController(WarrantyClaimService service,com.ke.ticketsystemke.service.WarrantyActionService actions,com.ke.ticketsystemke.service.WarrantyResolutionService resolutions,com.ke.ticketsystemke.service.WarrantyReplacementService replacements){this.service=service;this.actions=actions;this.resolutions=resolutions;this.replacements=replacements;}
 @GetMapping public ResponseEntity<WarrantyClaimResponse> get(@PathVariable Long ticketId,Authentication auth){WarrantyClaimResponse response=service.get(ticketId,auth.getName());return response==null?ResponseEntity.noContent().build():ResponseEntity.ok(response);}
 @PostMapping public ResponseEntity<WarrantyClaimResponse> create(@PathVariable Long ticketId,@Valid @RequestBody(required=false) CreateWarrantyClaimRequest request,Authentication auth){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(ticketId,request==null?new CreateWarrantyClaimRequest():request,auth.getName()));}
 @PatchMapping("/{claimId}") public WarrantyClaimResponse update(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody UpdateWarrantyClaimRequest request,Authentication auth){return service.update(ticketId,claimId,request,auth.getName());}
 @GetMapping("/{claimId}/events") public WarrantyClaimEventPageResponse events(@PathVariable Long ticketId,@PathVariable Long claimId,@RequestParam(required=false) Integer page,@RequestParam(required=false) Integer size,Authentication auth){return service.history(ticketId,claimId,page,size,auth.getName());}
 @PostMapping("/{claimId}/actions/complaint-registration-pending") public WarrantyClaimResponse complaintPending(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody MarkComplaintRegistrationPendingRequest request,Authentication auth){return actions.markComplaintPending(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/register-complaint") public WarrantyClaimResponse registerComplaint(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody RegisterWarrantyComplaintRequest request,Authentication auth){return actions.registerComplaint(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/schedule-visit") public WarrantyClaimResponse scheduleVisit(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody ScheduleWarrantyVisitRequest request,Authentication auth){return actions.scheduleVisit(ticketId,claimId,request,auth.getName());}
 @PatchMapping("/{claimId}/visit") public WarrantyClaimResponse updateVisit(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody UpdateExpectedWarrantyVisitRequest request,Authentication auth){return actions.updateExpectedVisit(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/record-visit") public WarrantyClaimResponse recordVisit(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody RecordWarrantyVisitRequest request,Authentication auth){return actions.recordVisit(ticketId,claimId,request,auth.getName());}
 @PutMapping("/{claimId}/follow-up") public WarrantyClaimResponse followUp(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody UpdateWarrantyFollowUpRequest request,Authentication auth){return actions.updateFollowUp(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/manufacturer-repair-done") public WarrantyResolutionResponse repairDone(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody ManufacturerRepairDoneRequest request,Authentication auth){return resolutions.manufacturerRepairDone(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/reject") public WarrantyResolutionResponse reject(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody RejectWarrantyRequest request,Authentication auth){return resolutions.reject(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/customer-decision") public WarrantyResolutionResponse customerDecision(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody RecordWarrantyCustomerDecisionRequest request,Authentication auth){return resolutions.customerDecision(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/customer-did-not-proceed") public WarrantyResolutionResponse didNotProceed(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody CustomerDidNotProceedRequest request,Authentication auth){return resolutions.customerDidNotProceed(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/replacement-approved") public WarrantyResolutionResponse replacementApproved(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody ReplacementApprovedRequest request,Authentication auth){return resolutions.replacementApproved(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/move-to-ready-delivery") public WarrantyResolutionResponse moveReady(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody WarrantyVersionRequest request,Authentication auth){return resolutions.moveToReadyDelivery(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/close") public WarrantyResolutionResponse close(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody CloseWarrantyClaimRequest request,Authentication auth){return resolutions.closeClaim(ticketId,claimId,request,auth.getName());}
 @GetMapping("/{claimId}/replacements") public java.util.List<WarrantyReplacementResponse> replacements(@PathVariable Long ticketId,@PathVariable Long claimId,Authentication auth){return replacements.list(ticketId,claimId,auth.getName());}
 @PostMapping("/{claimId}/replacements") public ResponseEntity<WarrantyClaimResponse> recordReplacement(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody ReplacementDetailsRequest request,Authentication auth){return ResponseEntity.status(HttpStatus.CREATED).body(replacements.create(ticketId,claimId,request,auth.getName()));}
 @PatchMapping("/{claimId}/replacements/{replacementId}") public WarrantyClaimResponse updateReplacement(@PathVariable Long ticketId,@PathVariable Long claimId,@PathVariable Long replacementId,@Valid @RequestBody ReplacementDetailsRequest request,Authentication auth){return replacements.update(ticketId,claimId,replacementId,request,auth.getName());}
 @PostMapping("/{claimId}/replacements/{replacementId}/supersede") public WarrantyClaimResponse supersedeReplacement(@PathVariable Long ticketId,@PathVariable Long claimId,@PathVariable Long replacementId,@Valid @RequestBody SupersedeWarrantyReplacementRequest request,Authentication auth){return replacements.supersede(ticketId,claimId,replacementId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/move-replacement-to-ready-delivery") public WarrantyResolutionResponse moveReplacementReady(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody WarrantyVersionRequest request,Authentication auth){return replacements.moveReady(ticketId,claimId,request,auth.getName());}
 @PostMapping("/{claimId}/actions/replacement-delivered") public WarrantyClaimResponse replacementDelivered(@PathVariable Long ticketId,@PathVariable Long claimId,@Valid @RequestBody ReplacementDeliveredRequest request,Authentication auth){return replacements.delivered(ticketId,claimId,request,auth.getName());}
}
