package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.entity.*; import com.ke.ticketsystemke.repository.*;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.time.*; import java.util.*; import java.util.function.*;
@Service
public class WarrantyClaimService {
 private final TicketRepository tickets; private final WarrantyClaimRepository claims; private final WarrantyClaimEventRepository events; private final WarrantyReplacementRepository replacements; private final EmployeeRepository employees; private final AccessService access; private final WarrantyPendingActionCalculator pending; private final WarrantyClaimEventService audit; private final WarrantyDocumentRequirementService documents;
 public WarrantyClaimService(TicketRepository tickets,WarrantyClaimRepository claims,WarrantyClaimEventRepository events,WarrantyReplacementRepository replacements,EmployeeRepository employees,AccessService access,WarrantyPendingActionCalculator pending,WarrantyClaimEventService audit,WarrantyDocumentRequirementService documents){this.tickets=tickets;this.claims=claims;this.events=events;this.replacements=replacements;this.employees=employees;this.access=access;this.pending=pending;this.audit=audit;this.documents=documents;}
 @Transactional(readOnly=true) public WarrantyClaimResponse get(Long ticketId,String actor){requireView(actor); Ticket t=ticket(ticketId); return claims.findByTicket_IdAndActiveTrue(ticketId).or(()->claims.findFirstByTicket_IdOrderByClaimSequenceDesc(ticketId)).map(c->response(c,t)).orElse(null);}
 @Transactional public WarrantyClaimResponse create(Long ticketId,CreateWarrantyClaimRequest req,String actor){access.requireAllowed(actor,AccessKey.VIEW_TICKETS);access.requireAllowed(actor,AccessKey.MANAGE_WARRANTY); Ticket t=ticket(ticketId); if(claims.existsByTicket_IdAndActiveTrue(ticketId)) conflict("An active warranty claim already exists");
  WarrantyClaim c=new WarrantyClaim(); c.setTicket(t); c.setClaimSequence(claims.findMaxClaimSequence(ticketId)+1); c.setActive(true); c.setState(WarrantyClaimState.DETAILS_REQUIRED); c.setResult(WarrantyClaimResult.PENDING); c.setCreatedByEmployeeId(actor); c.setUpdatedByEmployeeId(actor); applyCreate(c,req);
  String requested=trim(req.getWarrantyOwnerEmployeeId()); String owner=requested!=null?requested:trim(t.getPickedByEmployeeId()); if(requested!=null) access.requireAllowed(actor,AccessKey.ASSIGN_TICKET); if(requested!=null)c.setWarrantyOwnerEmployeeId(activeEmployee(requested).getEmployeeId());else if(owner!=null)employees.findByEmployeeIdIgnoreCase(owner).filter(Employee::isActive).ifPresent(e->c.setWarrantyOwnerEmployeeId(e.getEmployeeId())); validate(c); deriveState(c);
  try{claims.saveAndFlush(c);}catch(DataIntegrityViolationException ex){conflict("An active warranty claim already exists");}
  audit.record(c,WarrantyClaimEventType.WARRANTY_CLAIM_CREATED,actor,"Warranty claim created",Map.of("claimSequence",c.getClaimSequence())); return response(c,t);
 }
 @Transactional public WarrantyClaimResponse update(Long ticketId,Long claimId,UpdateWarrantyClaimRequest req,String actor){access.requireAllowed(actor,AccessKey.VIEW_TICKETS);access.requireAllowed(actor,AccessKey.MANAGE_WARRANTY); Ticket t=ticket(ticketId); WarrantyClaim c=claim(ticketId,claimId); if(!c.isActive()) conflict("Inactive warranty claims are read-only"); if(!Objects.equals(c.getVersion(),req.getVersion())) conflict("Warranty claim was updated by another user");
  Map<String,Object> changes=new LinkedHashMap<>(); WarrantyClaimState oldState=c.getState(); String oldOwner=c.getWarrantyOwnerEmployeeId(); applyPatch(c,req,changes);
  if(req.supplied("warrantyOwnerEmployeeId")){access.requireAllowed(actor,AccessKey.ASSIGN_TICKET); String owner=trim(req.getWarrantyOwnerEmployeeId()); if(owner!=null) owner=activeEmployee(owner).getEmployeeId(); c.setWarrantyOwnerEmployeeId(owner); changed(changes,"warrantyOwnerEmployeeId",oldOwner,owner);}
  if(req.supplied("state")){if(req.getState()!=WarrantyClaimState.DETAILS_REQUIRED&&req.getState()!=WarrantyClaimState.COMPLAINT_REQUIRED&&req.getState()!=WarrantyClaimState.CLOSED) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Operational warranty states must be changed through a warranty action"); c.setState(req.getState()); if(req.getState()==WarrantyClaimState.CLOSED){c.setActive(false);c.setResolvedAt(Instant.now());}}
  else deriveState(c); c.setUpdatedByEmployeeId(actor); validate(c); claims.saveAndFlush(c);
  if(!Objects.equals(oldOwner,c.getWarrantyOwnerEmployeeId())) audit.record(c,WarrantyClaimEventType.WARRANTY_OWNER_CHANGED,actor,"Warranty owner changed",Map.of("previousOwner",safe(oldOwner),"newOwner",safe(c.getWarrantyOwnerEmployeeId())));
  Map<String,Object> detailChanges=new LinkedHashMap<>(changes); detailChanges.remove("warrantyOwnerEmployeeId"); if(!detailChanges.isEmpty()) audit.record(c,WarrantyClaimEventType.WARRANTY_DETAILS_UPDATED,actor,"Warranty details updated",detailChanges);
  if(oldState!=c.getState()) audit.record(c,c.getState()==WarrantyClaimState.CLOSED?WarrantyClaimEventType.WARRANTY_CLAIM_CLOSED:WarrantyClaimEventType.WARRANTY_STATE_CHANGED,actor,c.getState()==WarrantyClaimState.CLOSED?"Warranty claim closed":"Warranty state changed",Map.of("previousState",oldState.name(),"newState",c.getState().name()));
  return response(c,t);
 }
 @Transactional(readOnly=true) public WarrantyClaimEventPageResponse history(Long ticketId,Long claimId,Integer page,Integer size,String actor){requireView(actor);ticket(ticketId);WarrantyClaim c=claim(ticketId,claimId);int p=page==null?0:page,s=size==null?20:Math.min(size,100);if(p<0||s<1)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid pagination");Page<WarrantyClaimEvent> data=events.findByWarrantyClaim_Id(c.getId(),PageRequest.of(p,s,Sort.by(Sort.Direction.DESC,"eventTimestamp")));return new WarrantyClaimEventPageResponse(ticketId,claimId,p,s,data.getTotalElements(),data.getTotalPages(),data.isFirst(),data.isLast(),data.map(WarrantyClaimEventResponse::from).getContent());}
 private void requireView(String actor){access.requireAllowed(actor,AccessKey.VIEW_TICKETS);access.requireAllowed(actor,AccessKey.VIEW_WARRANTY);}
 private Ticket ticket(Long id){return tickets.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Ticket not found"));}
 private WarrantyClaim claim(Long ticketId,Long claimId){WarrantyClaim c=claims.findById(claimId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Warranty claim not found"));if(!c.getTicket().getId().equals(ticketId))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Warranty claim not found");return c;}
 private Employee activeEmployee(String id){Employee e=employees.findByEmployeeIdIgnoreCase(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Employee not found"));if(!e.isActive())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Warranty owner must be an active employee");return e;}
 private void applyCreate(WarrantyClaim c,CreateWarrantyClaimRequest r){c.setBillingDate(r.getBillingDate());c.setWarrantyStartDate(r.getWarrantyStartDate());c.setWarrantyEndDate(r.getWarrantyEndDate());c.setManufacturerName(trim(r.getManufacturerName()));c.setProductSerialNumber(trim(r.getProductSerialNumber()));c.setModelNumber(trim(r.getModelNumber()));c.setManufacturerComplaintNumber(trim(r.getManufacturerComplaintNumber()));c.setComplaintRegisteredDate(r.getComplaintRegisteredDate());c.setExpectedVisitDate(r.getExpectedVisitDate());c.setManufacturerEngineerName(trim(r.getManufacturerEngineerName()));c.setManufacturerEngineerMobile(normalizePhone(r.getManufacturerEngineerMobile()));c.setManufacturerServiceCenterName(trim(r.getManufacturerServiceCenterName()));c.setWarrantyNotes(trim(r.getWarrantyNotes()));c.setNextFollowUpDate(r.getNextFollowUpDate());}
 private void applyPatch(WarrantyClaim c,UpdateWarrantyClaimRequest r,Map<String,Object> changes){patch(r,"billingDate",c.getBillingDate(),r.getBillingDate(),c::setBillingDate,changes);patch(r,"warrantyStartDate",c.getWarrantyStartDate(),r.getWarrantyStartDate(),c::setWarrantyStartDate,changes);patch(r,"warrantyEndDate",c.getWarrantyEndDate(),r.getWarrantyEndDate(),c::setWarrantyEndDate,changes);patch(r,"manufacturerName",c.getManufacturerName(),trim(r.getManufacturerName()),c::setManufacturerName,changes);patch(r,"productSerialNumber",c.getProductSerialNumber(),trim(r.getProductSerialNumber()),c::setProductSerialNumber,changes);patch(r,"modelNumber",c.getModelNumber(),trim(r.getModelNumber()),c::setModelNumber,changes);patch(r,"manufacturerComplaintNumber",c.getManufacturerComplaintNumber(),trim(r.getManufacturerComplaintNumber()),c::setManufacturerComplaintNumber,changes);patch(r,"complaintRegisteredDate",c.getComplaintRegisteredDate(),r.getComplaintRegisteredDate(),c::setComplaintRegisteredDate,changes);patch(r,"expectedVisitDate",c.getExpectedVisitDate(),r.getExpectedVisitDate(),c::setExpectedVisitDate,changes);patch(r,"manufacturerEngineerName",c.getManufacturerEngineerName(),trim(r.getManufacturerEngineerName()),c::setManufacturerEngineerName,changes);patch(r,"manufacturerEngineerMobile",c.getManufacturerEngineerMobile(),normalizePhone(r.getManufacturerEngineerMobile()),c::setManufacturerEngineerMobile,changes);patch(r,"manufacturerServiceCenterName",c.getManufacturerServiceCenterName(),trim(r.getManufacturerServiceCenterName()),c::setManufacturerServiceCenterName,changes);patch(r,"warrantyNotes",c.getWarrantyNotes(),trim(r.getWarrantyNotes()),c::setWarrantyNotes,changes);patch(r,"nextFollowUpDate",c.getNextFollowUpDate(),r.getNextFollowUpDate(),c::setNextFollowUpDate,changes);}
 private <T> void patch(UpdateWarrantyClaimRequest r,String f,T old,T value,Consumer<T> setter,Map<String,Object> changes){if(r.supplied(f)){setter.accept(value);changed(changes,f,old,value);}}
 private void changed(Map<String,Object> m,String f,Object old,Object value){if(!Objects.equals(old,value))m.put(f,Map.of("old",safe(old),"new",safe(value)));}
 private void validate(WarrantyClaim c){if(c.getWarrantyStartDate()!=null&&c.getWarrantyEndDate()!=null&&c.getWarrantyEndDate().isBefore(c.getWarrantyStartDate()))bad("Warranty end date cannot be before warranty start date");if(c.getBillingDate()!=null&&c.getWarrantyStartDate()!=null&&c.getWarrantyStartDate().isBefore(c.getBillingDate()))bad("Warranty start date cannot be before billing date");if(c.getBillingDate()!=null&&c.getComplaintRegisteredDate()!=null&&c.getComplaintRegisteredDate().isBefore(c.getBillingDate().minusYears(1)))bad("Complaint registered date is unreasonably before billing date");}
 private void deriveState(WarrantyClaim c){if(c.getState()!=WarrantyClaimState.DETAILS_REQUIRED&&c.getState()!=WarrantyClaimState.COMPLAINT_REQUIRED)return;if(c.getManufacturerName()==null||(c.getProductSerialNumber()==null&&c.getModelNumber()==null))c.setState(WarrantyClaimState.DETAILS_REQUIRED);else c.setState(WarrantyClaimState.COMPLAINT_REQUIRED);}
  public WarrantyClaimResponse response(WarrantyClaim c,Ticket t){String owner=c.getWarrantyOwnerEmployeeId();WarrantyOwnerResponse o=owner==null?null:new WarrantyOwnerResponse(owner,employees.findByEmployeeIdIgnoreCase(owner).map(Employee::getName).orElse(null));WarrantyReplacement r=replacements.findByWarrantyClaim_IdAndActiveTrue(c.getId()).orElse(null);return new WarrantyClaimResponse(c.getId(),t.getId(),t.getTicketNumber(),c.getClaimSequence(),c.isActive(),c.getState(),c.getResult(),c.getBillingDate(),c.getWarrantyStartDate(),c.getWarrantyEndDate(),c.getManufacturerName(),c.getProductSerialNumber(),c.getModelNumber(),c.getManufacturerComplaintNumber(),c.getComplaintRegisteredDate(),c.getExpectedVisitDate(),c.getManufacturerEngineerName(),c.getComplaintRegistrationAttemptDate(),c.getComplaintContactMethod(),c.getComplaintAttemptNotes(),c.getActualVisitDate(),c.getVisitOutcome(),c.getVisitNotes(),c.getManufacturerEngineerMobile(),c.getManufacturerServiceCenterName(),c.getWarrantyNotes(),c.getNextFollowUpDate(),c.getFollowUpNotes(),c.getFollowUpSource(),o,pending.calculate(c,r),c.getVersion(),c.getMarkedWarrantyAt(),c.getResolvedAt(),c.getManufacturerRepairCompletedAt(),c.getManufacturerRepairCompletionDate(),c.getManufacturerRepairCompletionNotes(),c.getManufacturerRepairReference(),c.getWarrantyRejectedAt(),c.getWarrantyRejectionDate(),c.getWarrantyRejectionReason(),c.getRejectionDecision(),c.getCustomerDecisionAt(),c.getCustomerDecisionDate(),c.getCustomerDecisionNotes(),c.getCustomerDidNotProceedAt(),c.getCustomerDidNotProceedDate(),c.getCustomerDidNotProceedReason(),c.getCustomerJourneyDecision(),c.getReplacementApprovedAt(),c.getReplacementApprovalDate(),c.getReplacementApprovalReference(),c.getExpectedReplacementDate(),c.getReplacementApprovalNotes(),c.getClaimClosedAt(),c.getClaimClosedByEmployeeId(),r==null?null:WarrantyReplacementResponse.from(r),c.getCreatedAt(),c.getUpdatedAt(),c.getCreatedByEmployeeId(),c.getUpdatedByEmployeeId());}
 private String trim(String v){return v==null||v.trim().isEmpty()?null:v.trim();} private String normalizePhone(String v){String x=trim(v);return x==null?null:x.replace(" ","").replace("-","");} private Object safe(Object v){return v==null?"":v;} private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} private void conflict(String m){throw new ResponseStatusException(HttpStatus.CONFLICT,m);}
}
