package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*;import com.ke.ticketsystemke.entity.*;import com.ke.ticketsystemke.repository.*;import org.slf4j.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;import java.util.stream.Collectors;
@Service public class WarrantyReminderGenerationService{
 private static final Logger log=LoggerFactory.getLogger(WarrantyReminderGenerationService.class);private static final ZoneId ZONE=ZoneId.of("Asia/Kolkata");
 private final WarrantyClaimRepository claims;private final WarrantyReplacementRepository replacements;private final WarrantyAttachmentRepository attachments;private final WarrantyReminderRepository reminders;private final WarrantyReminderGenerationRunRepository runs;private final EmployeeRepository employees;private final WarrantyPendingActionCalculator pending;private final WarrantyDocumentRequirementService documents;
 @Value("${warranty.reminders.long-pending-days:${WARRANTY_LONG_PENDING_DAYS:30}}")int longPendingDays;@Value("${warranty.reminders.escalation-level-1-days:${WARRANTY_ESCALATION_LEVEL_1_DAYS:2}}")int level1;@Value("${warranty.reminders.escalation-level-2-days:${WARRANTY_ESCALATION_LEVEL_2_DAYS:5}}")int level2;@Value("${warranty.reminders.escalation-level-3-days:${WARRANTY_ESCALATION_LEVEL_3_DAYS:10}}")int level3;
 public WarrantyReminderGenerationService(WarrantyClaimRepository c,WarrantyReplacementRepository r,WarrantyAttachmentRepository a,WarrantyReminderRepository m,WarrantyReminderGenerationRunRepository g,EmployeeRepository e,WarrantyPendingActionCalculator p,WarrantyDocumentRequirementService d){claims=c;replacements=r;attachments=a;reminders=m;runs=g;employees=e;pending=p;documents=d;}
 @Transactional public synchronized WarrantyReminderGenerationResponse generate(){LocalDate today=LocalDate.now(ZONE);WarrantyReminderGenerationRun run=new WarrantyReminderGenerationRun();run.setStartedAt(Instant.now());run.setBusinessDate(today);run.setStatus("RUNNING");run=runs.save(run);int scanned=0,created=0,updated=0,resolved=0,failures=0;List<String> errors=new ArrayList<>();
  List<WarrantyClaim> all=claims.findAllForTracker().stream().filter(c->c.isActive()&&c.getState()!=WarrantyClaimState.CLOSED&&c.getState()!=WarrantyClaimState.RESOLVED).toList();scanned=all.size();List<Long> ids=all.stream().map(WarrantyClaim::getId).toList();Map<Long,WarrantyReplacement> repl=ids.isEmpty()?Map.of():replacements.findByWarrantyClaim_IdInAndActiveTrue(ids).stream().collect(Collectors.toMap(r->r.getWarrantyClaim().getId(),r->r));Map<Long,Set<WarrantyAttachmentCategory>> docs=new HashMap<>();if(!ids.isEmpty())for(Object[] x:attachments.findActiveCategoriesByClaimIds(ids))docs.computeIfAbsent((Long)x[0],k->EnumSet.noneOf(WarrantyAttachmentCategory.class)).add((WarrantyAttachmentCategory)x[1]);Set<String> ownerIds=all.stream().map(WarrantyClaim::getWarrantyOwnerEmployeeId).filter(Objects::nonNull).map(x->x.toLowerCase(Locale.ROOT)).collect(Collectors.toSet());Map<String,String> names=ownerIds.isEmpty()?Map.of():employees.findByEmployeeIdLowercaseIn(ownerIds).stream().collect(Collectors.toMap(e->e.getEmployeeId().toLowerCase(Locale.ROOT),Employee::getName));Set<String> relevant=new HashSet<>();
  for(WarrantyClaim c:all)try{for(Fact f:facts(c,repl.get(c.getId()),docs.getOrDefault(c.getId(),Set.of()),today)){String recipient=c.getWarrantyOwnerEmployeeId();String key=key(c,f,recipient);relevant.add(key);WarrantyReminder existing=reminders.findByDeduplicationKey(key).orElse(null);if(existing==null){WarrantyReminder n=new WarrantyReminder();apply(n,c,f,recipient,names,today);n.setDeduplicationKey(key);try{reminders.saveAndFlush(n);created++;}catch(DataIntegrityViolationException race){log.info("event=warranty_reminder_deduplicated keyHash={}",key.hashCode());}}else{apply(existing,c,f,recipient,names,today);if(existing.getStatus()==WarrantyReminderStatus.SNOOZED&&existing.getSnoozedUntil()!=null&&!existing.getSnoozedUntil().isAfter(Instant.now()))existing.setStatus(WarrantyReminderStatus.OPEN);reminders.save(existing);updated++;}}}catch(RuntimeException ex){failures++;if(errors.size()<10)errors.add("claim "+c.getId()+": "+ex.getClass().getSimpleName());log.error("event=warranty_reminder_claim_failed claimId={}",c.getId(),ex);}
  for(WarrantyReminder r:reminders.findByStatusIn(List.of(WarrantyReminderStatus.OPEN,WarrantyReminderStatus.ACKNOWLEDGED,WarrantyReminderStatus.SNOOZED))){if(!relevant.contains(r.getDeduplicationKey())){boolean activeClaim=all.stream().anyMatch(c->c.getId().equals(r.getWarrantyClaim().getId()));r.setStatus(activeClaim?WarrantyReminderStatus.SUPERSEDED:WarrantyReminderStatus.RESOLVED);r.setResolvedAt(Instant.now());r.setResolvedReason(activeClaim?"Reminder condition or responsibility changed":"Underlying warranty condition resolved");reminders.save(r);resolved++;}}
  run.setCompletedAt(Instant.now());run.setStatus(failures==0?"COMPLETED":"COMPLETED_WITH_FAILURES");run.setClaimsScanned(scanned);run.setRemindersCreated(created);run.setRemindersUpdated(updated);run.setRemindersResolved(resolved);run.setFailures(failures);run.setErrorSummary(errors.isEmpty()?null:String.join("; ",errors));runs.save(run);return new WarrantyReminderGenerationResponse(run.getId(),today,scanned,created,updated,resolved,failures);}
 private List<Fact> facts(WarrantyClaim c,WarrantyReplacement r,Set<WarrantyAttachmentCategory> present,LocalDate today){List<Fact> out=new ArrayList<>();WarrantyPendingActionResponse p=pending.calculate(c,r);LocalDate due=p.dueDate();String code=p.code();if("ASSIGN_WARRANTY_OWNER".equals(code))out.add(f(WarrantyReminderType.WARRANTY_OWNER_MISSING,null,"Warranty owner missing","Assign a warranty owner so future actions have a responsible employee.","WARRANTY_OWNER_MISSING",false,today));
  if("REGISTER_MANUFACTURER_COMPLAINT".equals(code))out.add(f(WarrantyReminderType.COMPLAINT_REGISTRATION_PENDING,due,"Complaint registration pending",p.label(),code,false,today));
  if(code!=null&&code.startsWith("FOLLOW_UP")){boolean over=due!=null&&due.isBefore(today);WarrantyReminderType type="FOLLOW_UP_COMPLAINT_REGISTRATION".equals(code)?WarrantyReminderType.COMPLAINT_FOLLOW_UP_DUE:over?WarrantyReminderType.FOLLOW_UP_OVERDUE:WarrantyReminderType.FOLLOW_UP_DUE;out.add(f(type,due,over?"Warranty follow-up overdue":"Warranty follow-up due",p.label(),code,over,today));}
  if(c.getExpectedVisitDate()!=null&&c.getActualVisitDate()==null&&!c.getExpectedVisitDate().isAfter(today)){boolean over=c.getExpectedVisitDate().isBefore(today);out.add(f(over?WarrantyReminderType.EXPECTED_VISIT_OVERDUE:WarrantyReminderType.EXPECTED_VISIT_DUE,c.getExpectedVisitDate(),over?"Expected visit overdue":"Expected visit due today","Record or reschedule the manufacturer visit.","EXPECTED_VISIT",over,today));}
  if("RECORD_WARRANTY_RESULT".equals(code))out.add(f(WarrantyReminderType.WARRANTY_RESULT_PENDING,null,"Warranty result pending",p.label(),code,false,today));
  if(c.getExpectedReplacementDate()!=null&&c.getState()==WarrantyClaimState.REPLACEMENT_APPROVED_AWAITING_PRODUCT&&!c.getExpectedReplacementDate().isAfter(today)){boolean over=c.getExpectedReplacementDate().isBefore(today);out.add(f(over?WarrantyReminderType.EXPECTED_REPLACEMENT_OVERDUE:WarrantyReminderType.EXPECTED_REPLACEMENT_DUE,c.getExpectedReplacementDate(),over?"Expected replacement overdue":"Expected replacement due today",p.label(),code,over,today));}
  if(c.getState()==WarrantyClaimState.REPLACEMENT_RECEIVED)out.add(f(WarrantyReminderType.REPLACEMENT_READY_FOR_DELIVERY,null,"Replacement ready for delivery",p.label(),code,false,today));if(c.getState()==WarrantyClaimState.DELIVERY_PENDING||c.getState()==WarrantyClaimState.MANUFACTURER_REPAIR_COMPLETED)out.add(f(WarrantyReminderType.READY_TO_DELIVER,null,"Warranty item ready to deliver",p.label(),code,false,today));if(c.getState()==WarrantyClaimState.WARRANTY_REJECTED_AWAITING_DECISION||c.getState()==WarrantyClaimState.CUSTOMER_DECISION_PENDING)out.add(f(WarrantyReminderType.AWAITING_CUSTOMER_DECISION,c.getWarrantyRejectionDate(),"Awaiting customer decision",p.label(),code,c.getWarrantyRejectionDate()!=null&&c.getWarrantyRejectionDate().isBefore(today),today));
  if(documents.billRuleApplies(c)&&!present.contains(WarrantyAttachmentCategory.BILL_IMAGE)&&c.getBillDocumentOverriddenAt()==null)out.add(f(WarrantyReminderType.REQUIRED_DOCUMENTS_MISSING,null,"Required warranty document missing","Upload the required bill image or record an authorized override.","BILL_IMAGE",false,today));
  LocalDate marked=(c.getMarkedWarrantyAt()==null?c.getCreatedAt():c.getMarkedWarrantyAt()).atZone(ZONE).toLocalDate();if(ChronoUnit.DAYS.between(marked,today)>longPendingDays)out.add(f(WarrantyReminderType.LONG_PENDING_WARRANTY_CASE,marked.plusDays(longPendingDays),"Long-pending warranty case","This active warranty case has exceeded the configured pending threshold.","LONG_PENDING",true,today));return out;}
 private Fact f(WarrantyReminderType t,LocalDate d,String title,String msg,String action,boolean overdue,LocalDate today){int days=d==null?0:(int)Math.max(0,ChronoUnit.DAYS.between(d,today));WarrantyEscalationLevel e=days>=level3?WarrantyEscalationLevel.LEVEL_3:days>=level2?WarrantyEscalationLevel.LEVEL_2:days>=level1?WarrantyEscalationLevel.LEVEL_1:WarrantyEscalationLevel.NONE;boolean escalatable=Set.of(WarrantyReminderType.FOLLOW_UP_OVERDUE,WarrantyReminderType.EXPECTED_VISIT_OVERDUE,WarrantyReminderType.EXPECTED_REPLACEMENT_OVERDUE,WarrantyReminderType.READY_TO_DELIVER,WarrantyReminderType.AWAITING_CUSTOMER_DECISION,WarrantyReminderType.LONG_PENDING_WARRANTY_CASE).contains(t);if(!escalatable)e=WarrantyEscalationLevel.NONE;WarrantyReminderPriority priority=e==WarrantyEscalationLevel.LEVEL_3||t==WarrantyReminderType.LONG_PENDING_WARRANTY_CASE?WarrantyReminderPriority.CRITICAL:overdue?WarrantyReminderPriority.HIGH:t==WarrantyReminderType.REQUIRED_DOCUMENTS_MISSING?WarrantyReminderPriority.LOW:WarrantyReminderPriority.NORMAL;return new Fact(t,d,title,msg,action,overdue,days,e,priority);}
 private String key(WarrantyClaim c,Fact f,String recipient){return c.getId()+"|"+f.type+"|"+(f.due==null?"NONE":f.due)+"|"+(recipient==null?"UNASSIGNED":recipient.toLowerCase(Locale.ROOT))+"|"+(f.type==WarrantyReminderType.REQUIRED_DOCUMENTS_MISSING?f.action:"");}
 private void apply(WarrantyReminder n,WarrantyClaim c,Fact f,String recipient,Map<String,String> names,LocalDate today){n.setWarrantyClaim(c);n.setTicket(c.getTicket());n.setReminderType(f.type);n.setPriority(f.priority);n.setRecipientEmployeeId(recipient);n.setRecipientEmployeeNameSnapshot(recipient==null?null:names.getOrDefault(recipient.toLowerCase(Locale.ROOT),recipient));n.setDueDate(f.due);n.setGeneratedForDate(today);n.setTitle(f.title);n.setMessage(f.message);n.setPendingActionCode(f.action);n.setOverdue(f.overdue);n.setDaysOverdue(f.days);n.setEscalationLevel(f.level);n.setEscalated(f.level!=WarrantyEscalationLevel.NONE);if(n.getStatus()==WarrantyReminderStatus.RESOLVED||n.getStatus()==WarrantyReminderStatus.SUPERSEDED){n.setStatus(WarrantyReminderStatus.OPEN);n.setResolvedAt(null);n.setResolvedReason(null);}}
 private record Fact(WarrantyReminderType type,LocalDate due,String title,String message,String action,boolean overdue,int days,WarrantyEscalationLevel level,WarrantyReminderPriority priority){}
}
