package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*;import com.ke.ticketsystemke.entity.*;import com.ke.ticketsystemke.repository.WarrantyAttachmentRepository;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import java.time.Instant;import java.util.*;
@Service public class WarrantyDocumentRequirementService{
 private final WarrantyAttachmentRepository attachments;private final Instant effectiveAt;
 public WarrantyDocumentRequirementService(WarrantyAttachmentRepository a,@Value("${warranty.documents.bill-rule-effective-at:9999-12-31T00:00:00Z}")String effective){attachments=a;effectiveAt=Instant.parse(effective);}
 public boolean billRuleApplies(WarrantyClaim c){return c.getCreatedAt()!=null&&!c.getCreatedAt().isBefore(effectiveAt);}public boolean billPresent(WarrantyClaim c){return attachments.existsByWarrantyClaim_IdAndWarrantyReplacementIsNullAndCategoryAndActiveTrue(c.getId(),WarrantyAttachmentCategory.BILL_IMAGE);}
 public WarrantyDocumentSummaryResponse summarize(WarrantyClaim c,WarrantyReplacement replacement){Set<WarrantyAttachmentCategory> present=EnumSet.noneOf(WarrantyAttachmentCategory.class);attachments.findByWarrantyClaim_IdOrderByUploadedAtDesc(c.getId()).stream().filter(WarrantyAttachment::isActive).forEach(a->present.add(a.getCategory()));boolean newRule=billRuleApplies(c),overridden=c.getBillDocumentOverrideReason()!=null;List<WarrantyDocumentRequirementResponse> r=new ArrayList<>();add(r,present,WarrantyAttachmentCategory.BILL_IMAGE,newRule,overridden,"Upload purchase bill");add(r,present,WarrantyAttachmentCategory.WARRANTY_CARD_IMAGE,false,false,"Upload warranty card");add(r,present,WarrantyAttachmentCategory.PRODUCT_SERIAL_NUMBER_IMAGE,false,false,"Upload product serial-number image");if(c.getManufacturerComplaintNumber()!=null)add(r,present,WarrantyAttachmentCategory.MANUFACTURER_SERVICE_SLIP,false,false,"Upload manufacturer service slip");if(replacement!=null){add(r,present,WarrantyAttachmentCategory.REPLACEMENT_PROOF,false,false,"Upload replacement proof");if(replacement.getNewSerialNumber()==null)add(r,present,WarrantyAttachmentCategory.REPLACEMENT_SERIAL_NUMBER_IMAGE,false,false,"Upload replacement serial-number image");}int req=(int)r.stream().filter(x->x.required()&&!x.present()).count(),recommended=(int)r.stream().filter(x->!x.required()&&!x.present()).count();return new WarrantyDocumentSummaryResponse(req==0,req,recommended,present.contains(WarrantyAttachmentCategory.BILL_IMAGE),present.contains(WarrantyAttachmentCategory.WARRANTY_CARD_IMAGE),present.contains(WarrantyAttachmentCategory.MANUFACTURER_SERVICE_SLIP),present.contains(WarrantyAttachmentCategory.REPLACEMENT_PROOF),List.copyOf(r));}
 private void add(List<WarrantyDocumentRequirementResponse> r,Set<WarrantyAttachmentCategory> p,WarrantyAttachmentCategory c,boolean required,boolean overridden,String label){boolean present=p.contains(c);r.add(new WarrantyDocumentRequirementResponse(c,required,present,overridden,required&&!present&&!overridden,label));}
}
