package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.entity.*; import com.ke.ticketsystemke.repository.*;
import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
import java.time.*; import java.util.*;
@Service
public class WarrantyActionService {
 private static final ZoneId BUSINESS_ZONE=ZoneId.of("Asia/Kolkata");
 private final TicketRepository tickets; private final WarrantyClaimRepository claims; private final AccessService access; private final WarrantyClaimEventService audit; private final WarrantyClaimService claimService; private final WarrantyDocumentRequirementService documents;
 public WarrantyActionService(TicketRepository tickets,WarrantyClaimRepository claims,AccessService access,WarrantyClaimEventService audit,WarrantyClaimService claimService,WarrantyDocumentRequirementService documents){this.tickets=tickets;this.claims=claims;this.access=access;this.audit=audit;this.claimService=claimService;this.documents=documents;}
 @Transactional public WarrantyClaimResponse registerComplaintWithDocuments(Long ticketId,Long claimId,RegisterWarrantyComplaintRequest r,String actor){WarrantyClaim c=claims.findById(claimId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Warranty claim not found"));if(documents.billRuleApplies(c)&&!documents.billPresent(c)){String reason=trim(r.billDocumentOverrideReason());if(reason==null)bad("Purchase bill image or manager override reason is required");access.requireAnyAllowed(actor,AccessKey.MANAGE_WARRANTY_DOCUMENTS,AccessKey.RESOLVE_WARRANTY);c.setBillDocumentOverrideReason(reason);c.setBillDocumentOverriddenAt(Instant.now());c.setBillDocumentOverriddenByEmployeeId(actor);audit.record(c,WarrantyClaimEventType.WARRANTY_DOCUMENT_REQUIREMENT_OVERRIDDEN,actor,"Purchase bill requirement overridden",Map.of("category","BILL_IMAGE","overrideReason",reason));}return registerComplaint(ticketId,claimId,r,actor);}
 @Transactional public WarrantyClaimResponse markComplaintPending(Long ticketId,Long claimId,MarkComplaintRegistrationPendingRequest r,String actor){Context x=context(ticketId,claimId,r.version(),actor);minimumDetails(x.claim());todayOrPast(r.attemptDate(),"Attempt date");futureOrToday(r.nextFollowUpDate(),"Next follow-up date");WarrantyClaim c=x.claim();c.setComplaintRegistrationAttemptDate(r.attemptDate());c.setComplaintContactMethod(r.contactMethod());c.setComplaintAttemptNotes(trim(r.notes()));setFollowUp(c,r.nextFollowUpDate(),trim(r.notes()),WarrantyFollowUpSource.MANUAL,actor);state(c,WarrantyClaimState.COMPLAINT_REGISTRATION_PENDING);save(c,actor);audit.record(c,WarrantyClaimEventType.WARRANTY_COMPLAINT_REGISTRATION_PENDING,actor,"Complaint registration marked pending",Map.of("attemptDate",r.attemptDate(),"contactMethod",r.contactMethod(),"nextFollowUpDate",r.nextFollowUpDate()));return claimService.response(c,x.ticket());}
 @Transactional public WarrantyClaimResponse registerComplaint(Long ticketId,Long claimId,RegisterWarrantyComplaintRequest r,String actor){Context x=context(ticketId,claimId,r.version(),actor);WarrantyClaim c=x.claim();minimumDetails(c);if(trim(r.manufacturerComplaintNumber())==null)bad("Manufacturer complaint number is required");if(r.complaintRegisteredDate()==null)bad("Complaint registered date is required");if(c.getBillingDate()!=null&&r.complaintRegisteredDate().isBefore(c.getBillingDate()))bad("Complaint registered date cannot be before billing date");LocalDate follow=r.nextFollowUpDate();WarrantyFollowUpSource source=WarrantyFollowUpSource.MANUAL;if(follow==null&&r.expectedVisitDate()!=null){follow=r.expectedVisitDate().plusDays(1);source=WarrantyFollowUpSource.EXPECTED_VISIT_DEFAULT;}if(follow==null)bad("Next follow-up date or expected visit date is required");futureOrToday(follow,"Next follow-up date");c.setManufacturerComplaintNumber(trim(r.manufacturerComplaintNumber()));c.setComplaintRegisteredDate(r.complaintRegisteredDate());c.setComplaintRegisteredAt(Instant.now());c.setExpectedVisitDate(r.expectedVisitDate());if(r.expectedVisitDate()!=null)c.setVisitScheduledAt(Instant.now());setFollowUp(c,follow,null,source,actor);state(c,r.expectedVisitDate()==null?WarrantyClaimState.VISIT_SCHEDULING_REQUIRED:WarrantyClaimState.VISIT_PENDING);save(c,actor);audit.record(c,WarrantyClaimEventType.WARRANTY_COMPLAINT_REGISTERED,actor,"Manufacturer complaint registered",Map.of("complaintNumber",c.getManufacturerComplaintNumber(),"registeredDate",r.complaintRegisteredDate(),"nextFollowUpDate",follow));return claimService.response(c,x.ticket());}
 @Transactional public WarrantyClaimResponse scheduleVisit(Long ticketId,Long claimId,ScheduleWarrantyVisitRequest r,String actor){Context x=context(ticketId,claimId,r.version(),actor);WarrantyClaim c=x.claim();requireComplaint(c);LocalDate follow=r.nextFollowUpDate()==null?r.expectedVisitDate().plusDays(1):r.nextFollowUpDate();WarrantyFollowUpSource source=r.nextFollowUpDate()==null?WarrantyFollowUpSource.EXPECTED_VISIT_DEFAULT:WarrantyFollowUpSource.MANUAL;futureOrToday(follow,"Next follow-up date");c.setExpectedVisitDate(r.expectedVisitDate());c.setManufacturerEngineerName(trim(r.engineerName()));c.setManufacturerEngineerMobile(phone(r.engineerMobile()));c.setManufacturerServiceCenterName(trim(r.serviceCenterName()));c.setVisitNotes(trim(r.visitNotes()));c.setVisitScheduledAt(Instant.now());setFollowUp(c,follow,null,source,actor);state(c,WarrantyClaimState.VISIT_PENDING);save(c,actor);audit.record(c,WarrantyClaimEventType.WARRANTY_VISIT_SCHEDULED,actor,"Manufacturer visit scheduled",Map.of("expectedVisitDate",r.expectedVisitDate(),"nextFollowUpDate",follow));return claimService.response(c,x.ticket());}
 @Transactional public WarrantyClaimResponse updateExpectedVisit(Long ticketId,Long claimId,UpdateExpectedWarrantyVisitRequest r,String actor){Context x=context(ticketId,claimId,r.version(),actor);WarrantyClaim c=x.claim();requireComplaint(c);LocalDate old=c.getExpectedVisitDate(),oldFollow=c.getNextFollowUpDate();c.setExpectedVisitDate(r.expectedVisitDate());c.setVisitScheduledAt(Instant.now());if(c.getFollowUpSource()==WarrantyFollowUpSource.EXPECTED_VISIT_DEFAULT)setFollowUp(c,r.expectedVisitDate().plusDays(1),c.getFollowUpNotes(),WarrantyFollowUpSource.EXPECTED_VISIT_DEFAULT,actor);state(c,WarrantyClaimState.VISIT_PENDING);save(c,actor);Map<String,Object> meta=new LinkedHashMap<>();meta.put("previousExpectedVisitDate",safe(old));meta.put("newExpectedVisitDate",r.expectedVisitDate());meta.put("changeReason",trim(r.changeReason()));meta.put("previousFollowUpDate",safe(oldFollow));meta.put("newFollowUpDate",safe(c.getNextFollowUpDate()));audit.record(c,WarrantyClaimEventType.WARRANTY_EXPECTED_VISIT_UPDATED,actor,"Expected manufacturer visit updated",meta);return claimService.response(c,x.ticket());}
 @Transactional public WarrantyClaimResponse recordVisit(Long ticketId,Long claimId,RecordWarrantyVisitRequest r,String actor){Context x=context(ticketId,claimId,r.version(),actor);WarrantyClaim c=x.claim();requireComplaint(c);todayOrPast(r.actualVisitDate(),"Actual visit date");c.setActualVisitDate(r.actualVisitDate());c.setVisitOutcome(r.visitOutcome());c.setVisitNotes(trim(r.visitNotes()));if(trim(r.engineerName())!=null)c.setManufacturerEngineerName(trim(r.engineerName()));if(trim(r.engineerMobile())!=null)c.setManufacturerEngineerMobile(phone(r.engineerMobile()));if(trim(r.serviceCenterName())!=null)c.setManufacturerServiceCenterName(trim(r.serviceCenterName()));if(r.nextFollowUpDate()!=null){futureOrToday(r.nextFollowUpDate(),"Next follow-up date");setFollowUp(c,r.nextFollowUpDate(),trim(r.visitNotes()),WarrantyFollowUpSource.MANUAL,actor);}c.setVisitRecordedAt(Instant.now());state(c,r.visitOutcome()==WarrantyVisitOutcome.ENGINEER_DID_NOT_VISIT?WarrantyClaimState.VISIT_PENDING:WarrantyClaimState.VISIT_COMPLETED_AWAITING_RESULT);save(c,actor);audit.record(c,WarrantyClaimEventType.WARRANTY_VISIT_RECORDED,actor,r.visitOutcome()==WarrantyVisitOutcome.ENGINEER_DID_NOT_VISIT?"Engineer did not visit":"Manufacturer visit recorded",Map.of("actualVisitDate",r.actualVisitDate(),"visitOutcome",r.visitOutcome()));return claimService.response(c,x.ticket());}
 @Transactional public WarrantyClaimResponse updateFollowUp(Long ticketId,Long claimId,UpdateWarrantyFollowUpRequest r,String actor){Context x=context(ticketId,claimId,r.version(),actor);WarrantyClaim c=x.claim();LocalDate old=c.getNextFollowUpDate();String notes=trim(r.followUpNotes());if(r.nextFollowUpDate()!=null){futureOrToday(r.nextFollowUpDate(),"Next follow-up date");if(old!=null&&old.isBefore(today())&&notes==null)bad("Follow-up notes are required when changing an overdue follow-up");setFollowUp(c,r.nextFollowUpDate(),notes,WarrantyFollowUpSource.MANUAL,actor);}else{if(notes==null)bad("Follow-up notes are required when clearing a follow-up");c.setNextFollowUpDate(null);c.setFollowUpNotes(notes);c.setFollowUpSource(null);c.setLastFollowUpScheduledAt(Instant.now());c.setLastFollowUpUpdatedByEmployeeId(actor);}save(c,actor);WarrantyClaimEventType type=r.nextFollowUpDate()==null?WarrantyClaimEventType.WARRANTY_FOLLOW_UP_CLEARED:(old==null?WarrantyClaimEventType.WARRANTY_FOLLOW_UP_SCHEDULED:WarrantyClaimEventType.WARRANTY_FOLLOW_UP_UPDATED);audit.record(c,type,actor,r.nextFollowUpDate()==null?"Warranty follow-up cleared":old==null?"Warranty follow-up scheduled":"Warranty follow-up updated",Map.of("previousFollowUpDate",safe(old),"newFollowUpDate",safe(r.nextFollowUpDate()),"notes",safe(notes)));return claimService.response(c,x.ticket());}
 private Context context(Long ticketId,Long claimId,Long version,String actor){access.requireAllowed(actor,AccessKey.VIEW_TICKETS);access.requireAllowed(actor,AccessKey.MANAGE_WARRANTY);Ticket t=tickets.findById(ticketId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Ticket not found"));WarrantyClaim c=claims.findById(claimId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Warranty claim not found"));if(!c.getTicket().getId().equals(ticketId))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Warranty claim not found");if(!c.isActive()||c.getState()==WarrantyClaimState.CLOSED||c.getState()==WarrantyClaimState.RESOLVED)conflict("Warranty claim is not editable");if(c.getResult()!=WarrantyClaimResult.PENDING)conflict("Warranty result is already final");if(!Objects.equals(c.getVersion(),version))conflict("Warranty claim was updated by another user");return new Context(t,c);}
 private void minimumDetails(WarrantyClaim c){if(c.getManufacturerName()==null)bad("Manufacturer name is required");if(c.getProductSerialNumber()==null&&c.getModelNumber()==null)bad("Product serial number or model number is required");}
 private void requireComplaint(WarrantyClaim c){if(c.getManufacturerComplaintNumber()==null||c.getComplaintRegisteredDate()==null)conflict("Manufacturer complaint must be registered first");}
 private void setFollowUp(WarrantyClaim c,LocalDate date,String notes,WarrantyFollowUpSource source,String actor){c.setNextFollowUpDate(date);c.setFollowUpNotes(notes);c.setFollowUpSource(source);c.setLastFollowUpScheduledAt(Instant.now());c.setLastFollowUpUpdatedByEmployeeId(actor);}
 private void state(WarrantyClaim c,WarrantyClaimState state){c.setState(state);} private void save(WarrantyClaim c,String actor){c.setUpdatedByEmployeeId(actor);claims.saveAndFlush(c);}
 private LocalDate today(){return LocalDate.now(BUSINESS_ZONE);} private void futureOrToday(LocalDate d,String label){if(d.isBefore(today()))bad(label+" cannot be in the past");}private void todayOrPast(LocalDate d,String label){if(d.isAfter(today()))bad(label+" cannot be in the future");}
 private String trim(String v){return v==null||v.trim().isEmpty()?null:v.trim();} private String phone(String v){String x=trim(v);return x==null?null:x.replace(" ","").replace("-","");}private Object safe(Object v){return v==null?"":v;}private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private void conflict(String m){throw new ResponseStatusException(HttpStatus.CONFLICT,m);}private record Context(Ticket ticket,WarrantyClaim claim){}
}
