package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.entity.*; import com.ke.ticketsystemke.repository.*;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.*; import org.springframework.test.util.ReflectionTestUtils; import org.springframework.web.server.ResponseStatusException;
import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class WarrantyResolutionServiceTest {
 @Mock TicketRepository tickets;@Mock WarrantyClaimRepository claims;@Mock AccessService access;@Mock WarrantyClaimEventService audit;@Mock WarrantyClaimService claimService;@Mock GenericTransitionExecutorService validator;@Mock WorkflowTransitionExecutionService executor;WarrantyResolutionService service;Ticket ticket;WarrantyClaim claim;LocalDate today=LocalDate.now(ZoneId.of("Asia/Kolkata"));
 @BeforeEach void setup(){service=new WarrantyResolutionService(tickets,claims,access,audit,claimService,validator,executor);ticket=new Ticket();ticket.setId(1L);ticket.setStatus(TicketStatus.IN_PROGRESS);ticket.setPickedByEmployeeId("TECH");claim=new WarrantyClaim();ReflectionTestUtils.setField(claim,"id",2L);ReflectionTestUtils.setField(claim,"version",0L);claim.setTicket(ticket);claim.setActive(true);claim.setState(WarrantyClaimState.VISIT_COMPLETED_AWAITING_RESULT);claim.setResult(WarrantyClaimResult.PENDING);claim.setManufacturerComplaintNumber("C1");claim.setComplaintRegisteredDate(today.minusDays(2));lenient().when(tickets.findById(1L)).thenReturn(Optional.of(ticket));lenient().when(claims.findById(2L)).thenReturn(Optional.of(claim));lenient().when(claims.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));}
 @Test void manufacturerRepairCompletionSetsOutcomeAndStopsReminders(){claim.setNextFollowUpDate(today.plusDays(1));service.manufacturerRepairDone(1L,2L,new ManufacturerRepairDoneRequest(today,"Repair complete",null,null,"REF",null,0L),"ADMIN");assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.MANUFACTURER_REPAIR_DONE);assertThat(claim.getState()).isEqualTo(WarrantyClaimState.MANUFACTURER_REPAIR_COMPLETED);assertThat(claim.getNextFollowUpDate()).isNull();verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_MANUFACTURER_REPAIR_COMPLETED),anyString(),anyString(),anyMap());unchangedOwner();}
 @Test void repairCompletionRequiresVisitOrOverride(){claim.setState(WarrantyClaimState.VISIT_PENDING);assertThatThrownBy(()->service.manufacturerRepairDone(1L,2L,new ManufacturerRepairDoneRequest(today,"Done",null,null,null,null,0L),"ADMIN")).hasMessageContaining("400");}
 @Test void moveReadyUsesConfiguredTransitionAndWritesWarrantyEvent(){repaired();var plan=mock(GenericTransitionExecutorService.GenericTransitionExecutionPlan.class);TicketResponse result=mock(TicketResponse.class);when(validator.prepareActionExecution(1L,WarrantyResolutionService.MOVE_READY,"ADMIN")).thenReturn(plan);when(executor.execute(eq(plan),eq("ADMIN"),any())).thenReturn(result);service.moveToReadyDelivery(1L,2L,new WarrantyVersionRequest(0L),"ADMIN");assertThat(claim.getState()).isEqualTo(WarrantyClaimState.DELIVERY_PENDING);verify(executor).execute(eq(plan),eq("ADMIN"),any());verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_MOVED_TO_READY_DELIVERY),anyString(),anyString(),anyMap());}
 @Test void missingTransitionReturnsConflictWithoutWarrantyChange(){repaired();when(validator.prepareActionExecution(1L,WarrantyResolutionService.MOVE_READY,"ADMIN")).thenThrow(new ResponseStatusException(HttpStatus.BAD_REQUEST,"missing"));assertThatThrownBy(()->service.moveToReadyDelivery(1L,2L,new WarrantyVersionRequest(0L),"ADMIN")).hasMessageContaining("409");assertThat(claim.getState()).isEqualTo(WarrantyClaimState.MANUFACTURER_REPAIR_COMPLETED);verifyNoInteractions(audit);}
 @Test void rejectionAwaitingDecisionDoesNotTouchTicketWorkflow(){service.reject(1L,2L,new RejectWarrantyRequest(today,"Rejected",WarrantyRejectionDecision.AWAIT_CUSTOMER_DECISION,null,0L),"ADMIN");assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.WARRANTY_REJECTED);assertThat(claim.getState()).isEqualTo(WarrantyClaimState.WARRANTY_REJECTED_AWAITING_DECISION);verifyNoInteractions(validator,executor);assertThat(ticket.getStatus()).isEqualTo(TicketStatus.IN_PROGRESS);}
 @Test void rejectedPaidRepairExecutesConfiguredTransitionAndPreservesHistory(){var plan=mock(GenericTransitionExecutorService.GenericTransitionExecutionPlan.class);when(validator.prepareActionExecution(1L,WarrantyResolutionService.CONTINUE_PAID,"ADMIN")).thenReturn(plan);when(executor.execute(eq(plan),eq("ADMIN"),any())).thenReturn(mock(TicketResponse.class));service.reject(1L,2L,new RejectWarrantyRequest(today,"Rejected",WarrantyRejectionDecision.CONTINUE_AS_PAID_REPAIR,null,0L),"ADMIN");assertThat(claim.isActive()).isFalse();assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.WARRANTY_REJECTED);verify(executor).execute(eq(plan),eq("ADMIN"),any());verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_CONTINUED_AS_PAID_REPAIR),anyString(),anyString(),anyMap());}
 @Test void customerDecisionCompletesPendingRejection(){claim.setResult(WarrantyClaimResult.WARRANTY_REJECTED);claim.setRejectionDecision(WarrantyRejectionDecision.AWAIT_CUSTOMER_DECISION);claim.setState(WarrantyClaimState.WARRANTY_REJECTED_AWAITING_DECISION);service.customerDecision(1L,2L,new RecordWarrantyCustomerDecisionRequest(WarrantyRejectionDecision.CLOSE_WARRANTY_CLAIM,today,"Close it",0L),"ADMIN");assertThat(claim.isActive()).isFalse();assertThat(claim.getCustomerDecisionAt()).isNotNull();}
 @Test void customerDidNotProceedRecordsSeparateJourneyDecision(){service.customerDidNotProceed(1L,2L,new CustomerDidNotProceedRequest(today,"Customer stopped",WarrantyCustomerJourneyDecision.AWAIT_CUSTOMER_COLLECTION,0L),"ADMIN");assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.CUSTOMER_DID_NOT_PROCEED);assertThat(claim.getState()).isEqualTo(WarrantyClaimState.CUSTOMER_DECISION_PENDING);assertThat(claim.isActive()).isTrue();verifyNoInteractions(executor);}
 @Test void replacementApprovalRemainsPendingAndDoesNotMoveTicket(){service.replacementApproved(1L,2L,new ReplacementApprovedRequest(today,"APR-1",null,today.plusDays(5),0L),"ADMIN");assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.PENDING);assertThat(claim.getState()).isEqualTo(WarrantyClaimState.REPLACEMENT_APPROVED_AWAITING_PRODUCT);assertThat(ticket.getStatus()).isEqualTo(TicketStatus.IN_PROGRESS);verifyNoInteractions(validator,executor);}
 @Test void staleResolutionReturnsConflict(){assertThatThrownBy(()->service.manufacturerRepairDone(1L,2L,new ManufacturerRepairDoneRequest(today,"Done",null,null,null,null,5L),"ADMIN")).hasMessageContaining("409");}
 @Test void managePermissionAloneCannotResolve(){doAnswer(invocation->{if(invocation.getArgument(1)==AccessKey.RESOLVE_WARRANTY)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Access denied");return null;}).when(access).requireAllowed(eq("TECH"),any(AccessKey.class));assertThatThrownBy(()->service.manufacturerRepairDone(1L,2L,new ManufacturerRepairDoneRequest(today,"Done",null,null,null,null,0L),"TECH")).hasMessageContaining("403");}
 @Test void warrantyAuditFailureAbortsCombinedOperation(){repaired();var plan=mock(GenericTransitionExecutorService.GenericTransitionExecutionPlan.class);when(validator.prepareActionExecution(anyLong(),anyString(),anyString())).thenReturn(plan);when(executor.execute(eq(plan),anyString(),any())).thenReturn(mock(TicketResponse.class));doThrow(new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"audit failed")).when(audit).record(any(),eq(WarrantyClaimEventType.WARRANTY_MOVED_TO_READY_DELIVERY),anyString(),anyString(),anyMap());assertThatThrownBy(()->service.moveToReadyDelivery(1L,2L,new WarrantyVersionRequest(0L),"ADMIN")).hasMessageContaining("500");}
 private void repaired(){claim.setResult(WarrantyClaimResult.MANUFACTURER_REPAIR_DONE);claim.setState(WarrantyClaimState.MANUFACTURER_REPAIR_COMPLETED);}private void unchangedOwner(){assertThat(ticket.getPickedByEmployeeId()).isEqualTo("TECH");}
}
