package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.entity.*; import org.junit.jupiter.api.Test; import java.time.*; import static org.assertj.core.api.Assertions.*;
class WarrantyPendingActionPhase2BTest {
 private final LocalDate today=LocalDate.of(2026,7,20); private final WarrantyPendingActionCalculator calculator=new WarrantyPendingActionCalculator(Clock.fixed(today.atStartOfDay(ZoneId.of("Asia/Kolkata")).toInstant(),ZoneId.of("Asia/Kolkata")));
 @Test void overdueVisitAndFollowUpUseManufacturerFollowUpAsPrimary(){WarrantyClaim c=registered();c.setExpectedVisitDate(today.minusDays(2));c.setNextFollowUpDate(today.minusDays(1));var result=calculator.calculate(c);assertThat(result.code()).isEqualTo("FOLLOW_UP_MANUFACTURER");assertThat(result.overdue()).isTrue();assertThat(result.reasons()).contains("EXPECTED_VISIT_OVERDUE","FOLLOW_UP_OVERDUE");}
 @Test void completedVisitRequestsFutureResultWithoutActionForm(){WarrantyClaim c=registered();c.setActualVisitDate(today);c.setVisitOutcome(WarrantyVisitOutcome.INSPECTION_COMPLETED);c.setState(WarrantyClaimState.VISIT_COMPLETED_AWAITING_RESULT);var result=calculator.calculate(c);assertThat(result.code()).isEqualTo("RECORD_WARRANTY_RESULT");assertThat(result.recommendedActionFormKey()).isNull();}
 @Test void complaintPendingFollowUpUsesBusinessDate(){WarrantyClaim c=base();c.setState(WarrantyClaimState.COMPLAINT_REGISTRATION_PENDING);c.setNextFollowUpDate(today.minusDays(3));var result=calculator.calculate(c);assertThat(result.code()).isEqualTo("FOLLOW_UP_COMPLAINT_REGISTRATION");assertThat(result.daysOverdue()).isEqualTo(3);}
 private WarrantyClaim base(){WarrantyClaim c=new WarrantyClaim();c.setActive(true);c.setResult(WarrantyClaimResult.PENDING);c.setWarrantyOwnerEmployeeId("E1");c.setManufacturerName("Maker");c.setModelNumber("M1");return c;}private WarrantyClaim registered(){WarrantyClaim c=base();c.setManufacturerComplaintNumber("C1");c.setComplaintRegisteredDate(today.minusDays(5));c.setState(WarrantyClaimState.VISIT_PENDING);return c;}
}
