package com.ke.ticketsystemke.service;import com.ke.ticketsystemke.dto.*;import com.ke.ticketsystemke.entity.*;import com.ke.ticketsystemke.repository.WarrantyReminderRepository;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.test.util.ReflectionTestUtils;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)class WarrantyReminderServiceTest{@Mock WarrantyReminderRepository repo;@Mock AccessService access;WarrantyReminderService service;WarrantyReminder reminder;
 @BeforeEach void setup(){service=new WarrantyReminderService(repo,access);ReflectionTestUtils.setField(service,"maxSnoozeDays",30);reminder=reminder();lenient().when(access.isAllowed(anyString(),eq(AccessKey.MANAGE_WARRANTY_REMINDERS))).thenReturn(false);lenient().when(repo.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void employeeSeesOnlyOwnReminder(){WarrantyReminder other=reminder();other.setRecipientEmployeeId("OTHER");when(repo.findAllDetailed()).thenReturn(List.of(reminder,other));WarrantyReminderPageResponse p=service.list(new WarrantyReminderFilter(),"EMP1");assertThat(p.totalElements()).isEqualTo(1);assertThat(p.content().getFirst().recipientEmployeeId()).isEqualTo("EMP1");}
 @Test void managerSeesUnassignedOrganizationQueue(){reminder.setRecipientEmployeeId(null);when(access.isAllowed("ADMIN",AccessKey.MANAGE_WARRANTY_REMINDERS)).thenReturn(true);when(repo.findAllDetailed()).thenReturn(List.of(reminder));WarrantyReminderFilter f=new WarrantyReminderFilter();f.setAssignedToMe(false);f.setUnassigned(true);assertThat(service.list(f,"ADMIN").totalElements()).isEqualTo(1);}
 @Test void acknowledgementPreservesPendingCondition(){when(repo.findById(1L)).thenReturn(Optional.of(reminder));WarrantyReminderResponse r=service.acknowledge(1L,new WarrantyReminderAcknowledgeRequest(0L,"Seen"),"EMP1");assertThat(r.status()).isEqualTo(WarrantyReminderStatus.ACKNOWLEDGED);assertThat(reminder.getResolvedAt()).isNull();}
 @Test void snoozeValidatesFutureAndVersion(){when(repo.findById(1L)).thenReturn(Optional.of(reminder));assertThatThrownBy(()->service.snooze(1L,new WarrantyReminderSnoozeRequest(0L,Instant.now().minusSeconds(1),"wait"),"EMP1")).hasMessageContaining("422");assertThatThrownBy(()->service.acknowledge(1L,new WarrantyReminderAcknowledgeRequest(4L,null),"EMP1")).hasMessageContaining("409");}
 @Test void dailySummaryUsesSamePersonalVisibility(){WarrantyReminder other=reminder();other.setRecipientEmployeeId("OTHER");when(repo.findAllDetailed()).thenReturn(List.of(reminder,other));WarrantyReminderDailySummary s=service.summary("EMP1");assertThat(s.assignedOpenReminders()).isEqualTo(1);assertThat(s.managerView()).isFalse();}
 private WarrantyReminder reminder(){Ticket t=new Ticket();t.setId(10L);t.setTicketNumber("KE-10");t.setCustomerName("Customer");t.setProductType("TV");WarrantyClaim c=new WarrantyClaim();ReflectionTestUtils.setField(c,"id",2L);c.setTicket(t);c.setManufacturerName("Maker");WarrantyReminder r=new WarrantyReminder();ReflectionTestUtils.setField(r,"id",1L);ReflectionTestUtils.setField(r,"version",0L);ReflectionTestUtils.setField(r,"createdAt",Instant.now());r.setWarrantyClaim(c);r.setTicket(t);r.setReminderType(WarrantyReminderType.FOLLOW_UP_OVERDUE);r.setStatus(WarrantyReminderStatus.OPEN);r.setPriority(WarrantyReminderPriority.HIGH);r.setRecipientEmployeeId("EMP1");r.setRecipientEmployeeNameSnapshot("Employee");r.setOverdue(true);r.setDaysOverdue(3);r.setEscalationLevel(WarrantyEscalationLevel.LEVEL_1);return r;}}
