package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*;import com.ke.ticketsystemke.entity.*;import com.ke.ticketsystemke.repository.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.test.util.ReflectionTestUtils;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class WarrantyReplacementServiceTest{
 @Mock TicketRepository tickets;@Mock WarrantyClaimRepository claims;@Mock WarrantyReplacementRepository replacements;@Mock AccessService access;@Mock WarrantyClaimEventService audit;@Mock WarrantyClaimService claimService;@Mock GenericTransitionExecutorService validator;@Mock WorkflowTransitionExecutionService executor;WarrantyReplacementService service;Ticket ticket;WarrantyClaim claim;LocalDate today=LocalDate.now(ZoneId.of("Asia/Kolkata"));
 @BeforeEach void setup(){service=new WarrantyReplacementService(tickets,claims,replacements,access,audit,claimService,validator,executor);ticket=new Ticket();ticket.setId(1L);ticket.setTicketNumber("KE-1");ticket.setStatus(TicketStatus.IN_PROGRESS);claim=new WarrantyClaim();ReflectionTestUtils.setField(claim,"id",2L);ReflectionTestUtils.setField(claim,"version",0L);claim.setTicket(ticket);claim.setActive(true);claim.setState(WarrantyClaimState.REPLACEMENT_APPROVED_AWAITING_PRODUCT);claim.setResult(WarrantyClaimResult.PENDING);lenient().when(tickets.findById(1L)).thenReturn(Optional.of(ticket));lenient().when(claims.findById(2L)).thenReturn(Optional.of(claim));lenient().when(replacements.findMaxSequence(2L)).thenReturn(0);lenient().when(replacements.saveAndFlush(any())).thenAnswer(i->{WarrantyReplacement r=i.getArgument(0);if(r.getId()==null)ReflectionTestUtils.setField(r,"id",10L);if(r.getVersion()==null)ReflectionTestUtils.setField(r,"version",0L);return r;});}
 @Test void recordsFirstReplacementWithoutChangingTicket(){service.create(1L,2L,details(" SN-1 ","REF-1",null),"ADMIN");assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.REPLACEMENT_DONE);assertThat(claim.getState()).isEqualTo(WarrantyClaimState.REPLACEMENT_RECEIVED);assertThat(ticket.getStatus()).isEqualTo(TicketStatus.IN_PROGRESS);ArgumentCaptor<WarrantyReplacement> c=ArgumentCaptor.forClass(WarrantyReplacement.class);verify(replacements).saveAndFlush(c.capture());assertThat(c.getValue().getNormalizedNewSerialNumber()).isEqualTo("SN1");verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_REPLACEMENT_RECEIVED),anyString(),anyString(),anyMap());}
 @Test void rejectsSecondActiveReplacement(){when(replacements.existsByWarrantyClaim_IdAndActiveTrue(2L)).thenReturn(true);assertThatThrownBy(()->service.create(1L,2L,details("S","R",null),"ADMIN")).hasMessageContaining("409");}
 @Test void serialOverrideStoresIncompleteReplacement(){service.create(1L,2L,details(null,"R","Serial label unavailable"),"ADMIN");ArgumentCaptor<WarrantyReplacement> c=ArgumentCaptor.forClass(WarrantyReplacement.class);verify(replacements).saveAndFlush(c.capture());assertThat(c.getValue().getSerialNumberOverrideReason()).isEqualTo("Serial label unavailable");assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.REPLACEMENT_DONE);}
 @Test void missingSerialAndOverrideIsRejected(){assertThatThrownBy(()->service.create(1L,2L,details(null,"R",null),"ADMIN")).hasMessageContaining("400");}
 @Test void staleClaimIsRejected(){assertThatThrownBy(()->service.create(1L,2L,new ReplacementDetailsRequest(today,"Product",null,null,"S",null,null,"R","Maker",null,null,null,9L,null),"ADMIN")).hasMessageContaining("409");}
 @Test void materialUpdateMustSupersede(){WarrantyReplacement r=replacement(true,"OLD");when(replacements.findById(10L)).thenReturn(Optional.of(r));claim.setState(WarrantyClaimState.REPLACEMENT_RECEIVED);claim.setResult(WarrantyClaimResult.REPLACEMENT_DONE);assertThatThrownBy(()->service.update(1L,2L,10L,details("NEW","R",null),"ADMIN")).hasMessageContaining("supersede");}
 @Test void supersedePreservesOldAndCreatesNextActive(){WarrantyReplacement old=replacement(true,"OLD");when(replacements.findById(10L)).thenReturn(Optional.of(old));when(replacements.findMaxSequence(2L)).thenReturn(1);claim.setState(WarrantyClaimState.REPLACEMENT_RECEIVED);claim.setResult(WarrantyClaimResult.REPLACEMENT_DONE);ReplacementDetailsRequest d=details("NEW","R2",null);service.supersede(1L,2L,10L,new SupersedeWarrantyReplacementRequest("Wrong serial",0L,0L,d),"ADMIN");assertThat(old.isActive()).isFalse();verify(replacements,times(2)).saveAndFlush(any());verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_REPLACEMENT_SUPERSEDED),anyString(),anyString(),anyMap());}
 @Test void deliveredClosesClaimAndKeepsReplacementActive(){WarrantyReplacement r=replacement(true,"S");when(replacements.findByWarrantyClaim_IdAndActiveTrue(2L)).thenReturn(Optional.of(r));ticket.setStatus(TicketStatus.COMPLETED);claim.setState(WarrantyClaimState.DELIVERY_PENDING);claim.setResult(WarrantyClaimResult.REPLACEMENT_DONE);service.delivered(1L,2L,new ReplacementDeliveredRequest(today,0L,0L),"ADMIN");assertThat(claim.isActive()).isFalse();assertThat(claim.getState()).isEqualTo(WarrantyClaimState.CLOSED);assertThat(r.isActive()).isTrue();assertThat(r.getReplacementGivenToCustomerDate()).isEqualTo(today);}
 private ReplacementDetailsRequest details(String serial,String ref,String override){return new ReplacementDetailsRequest(today,"Product",null,"Model",serial,null,null,ref,"Manufacturer",null,override,null,0L,0L);}private WarrantyReplacement replacement(boolean active,String serial){WarrantyReplacement r=new WarrantyReplacement();ReflectionTestUtils.setField(r,"id",10L);ReflectionTestUtils.setField(r,"version",0L);r.setWarrantyClaim(claim);r.setReplacementSequence(1);r.setActive(active);r.setReplacementReceivedDate(today.minusDays(1));r.setNewProductName("Product");r.setNewModelNumber("Model");r.setNewSerialNumber(serial);r.setReplacementReferenceNumber("R");r.setReplacementProvidedBy("Maker");return r;}
}
