package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.entity.*; import com.ke.ticketsystemke.repository.*;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.test.util.ReflectionTestUtils; import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDate; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class WarrantyClaimServiceTest {
 @Mock TicketRepository tickets; @Mock WarrantyClaimRepository claims; @Mock WarrantyClaimEventRepository events; @Mock EmployeeRepository employees; @Mock AccessService access; @Mock WarrantyClaimEventService audit;
 WarrantyClaimService service; Ticket ticket;
 @BeforeEach void setup(){service=new WarrantyClaimService(tickets,claims,events,employees,access,new WarrantyPendingActionCalculator(),audit);ticket=new Ticket();ticket.setId(7L);ticket.setTicketNumber("KE-7");ticket.setStatus(TicketStatus.IN_PROGRESS);ticket.setPickedByEmployeeId("TECH1");lenient().when(tickets.findById(7L)).thenReturn(Optional.of(ticket));lenient().when(claims.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));}
 @Test void createsFirstClaimWithoutChangingTicketWorkflow(){when(claims.existsByTicket_IdAndActiveTrue(7L)).thenReturn(false);when(claims.findMaxClaimSequence(7L)).thenReturn(0);Employee owner=employee("TECH1","Technician");when(employees.findByEmployeeIdIgnoreCase("TECH1")).thenReturn(Optional.of(owner));WarrantyClaimResponse result=service.create(7L,new CreateWarrantyClaimRequest(),"ADMIN1");assertThat(result.claimSequence()).isEqualTo(1);assertThat(result.result()).isEqualTo(WarrantyClaimResult.PENDING);assertThat(ticket.getStatus()).isEqualTo(TicketStatus.IN_PROGRESS);verify(audit).record(any(),eq(WarrantyClaimEventType.WARRANTY_CLAIM_CREATED),eq("ADMIN1"),anyString(),anyMap());}
 @Test void rejectsSecondActiveClaim(){when(claims.existsByTicket_IdAndActiveTrue(7L)).thenReturn(true);assertThatThrownBy(()->service.create(7L,new CreateWarrantyClaimRequest(),"ADMIN1")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("409");}
 @Test void staleUpdateIsRejectedAndOwnerDoesNotChangeTicketOwner(){WarrantyClaim claim=claim();ReflectionTestUtils.setField(claim,"id",11L);ReflectionTestUtils.setField(claim,"version",3L);when(claims.findById(11L)).thenReturn(Optional.of(claim));UpdateWarrantyClaimRequest stale=new UpdateWarrantyClaimRequest();stale.setVersion(2L);assertThatThrownBy(()->service.update(7L,11L,stale,"ADMIN1")).hasMessageContaining("409");assertThat(ticket.getPickedByEmployeeId()).isEqualTo("TECH1");}
 @Test void updatesDetailsAndAuditsStateWithoutChangingTicket(){WarrantyClaim claim=claim();ReflectionTestUtils.setField(claim,"id",11L);ReflectionTestUtils.setField(claim,"version",0L);when(claims.findById(11L)).thenReturn(Optional.of(claim));UpdateWarrantyClaimRequest request=new UpdateWarrantyClaimRequest();request.setVersion(0L);request.setManufacturerName("Maker");request.setModelNumber("M1");service.update(7L,11L,request,"ADMIN1");assertThat(claim.getState()).isEqualTo(WarrantyClaimState.COMPLAINT_REQUIRED);assertThat(ticket.getStatus()).isEqualTo(TicketStatus.IN_PROGRESS);verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_DETAILS_UPDATED),eq("ADMIN1"),anyString(),anyMap());verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_STATE_CHANGED),eq("ADMIN1"),anyString(),anyMap());}
 @Test void ownerChangeRequiresAssignmentPermissionAndLeavesTicketOwnerAlone(){WarrantyClaim claim=claim();ReflectionTestUtils.setField(claim,"id",11L);ReflectionTestUtils.setField(claim,"version",0L);when(claims.findById(11L)).thenReturn(Optional.of(claim));when(employees.findByEmployeeIdIgnoreCase("OFFICE1")).thenReturn(Optional.of(employee("OFFICE1","Office")));UpdateWarrantyClaimRequest request=new UpdateWarrantyClaimRequest();request.setVersion(0L);request.setWarrantyOwnerEmployeeId("OFFICE1");service.update(7L,11L,request,"ADMIN1");verify(access).requireAllowed("ADMIN1",AccessKey.ASSIGN_TICKET);assertThat(claim.getWarrantyOwnerEmployeeId()).isEqualTo("OFFICE1");assertThat(ticket.getPickedByEmployeeId()).isEqualTo("TECH1");verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_OWNER_CHANGED),eq("ADMIN1"),anyString(),anyMap());}
 @Test void rejectsInvalidWarrantyDateOrder(){WarrantyClaim claim=claim();ReflectionTestUtils.setField(claim,"id",11L);ReflectionTestUtils.setField(claim,"version",0L);when(claims.findById(11L)).thenReturn(Optional.of(claim));UpdateWarrantyClaimRequest request=new UpdateWarrantyClaimRequest();request.setVersion(0L);request.setWarrantyStartDate(LocalDate.of(2026,2,1));request.setWarrantyEndDate(LocalDate.of(2026,1,1));assertThatThrownBy(()->service.update(7L,11L,request,"ADMIN1")).hasMessageContaining("400");}
 private WarrantyClaim claim(){WarrantyClaim c=new WarrantyClaim();c.setTicket(ticket);c.setClaimSequence(1);c.setActive(true);c.setState(WarrantyClaimState.DETAILS_REQUIRED);c.setResult(WarrantyClaimResult.PENDING);c.setCreatedByEmployeeId("ADMIN1");c.setUpdatedByEmployeeId("ADMIN1");return c;}
 private Employee employee(String id,String name){Employee e=new Employee();e.setEmployeeId(id);e.setName(name);e.setActive(true);return e;}
}
