package com.ke.ticketsystemke.service;
import com.ke.ticketsystemke.dto.*; import com.ke.ticketsystemke.entity.*; import com.ke.ticketsystemke.repository.*;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.HttpStatus; import org.springframework.test.util.ReflectionTestUtils; import org.springframework.web.server.ResponseStatusException;
import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class WarrantyActionServiceTest {
 @Mock TicketRepository tickets; @Mock WarrantyClaimRepository claims; @Mock AccessService access; @Mock WarrantyClaimEventService audit; @Mock WarrantyClaimService claimService; @Mock WarrantyDocumentRequirementService documents; WarrantyActionService service; Ticket ticket; WarrantyClaim claim; LocalDate today=LocalDate.now(ZoneId.of("Asia/Kolkata"));
 @BeforeEach void setup(){service=new WarrantyActionService(tickets,claims,access,audit,claimService,documents);ticket=new Ticket();ticket.setId(1L);ticket.setStatus(TicketStatus.IN_PROGRESS);ticket.setPickedByEmployeeId("TECH");claim=new WarrantyClaim();ReflectionTestUtils.setField(claim,"id",2L);ReflectionTestUtils.setField(claim,"version",0L);claim.setTicket(ticket);claim.setActive(true);claim.setState(WarrantyClaimState.COMPLAINT_REQUIRED);claim.setResult(WarrantyClaimResult.PENDING);claim.setManufacturerName("Maker");claim.setModelNumber("M1");claim.setWarrantyOwnerEmployeeId("OWNER");lenient().when(tickets.findById(1L)).thenReturn(Optional.of(ticket));lenient().when(claims.findById(2L)).thenReturn(Optional.of(claim));lenient().when(claims.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));}
 @Test void complaintPendingSucceedsAndAudits(){service.markComplaintPending(1L,2L,new MarkComplaintRegistrationPendingRequest(today,WarrantyContactMethod.PHONE,"Called",today.plusDays(1),0L),"ADMIN");assertThat(claim.getState()).isEqualTo(WarrantyClaimState.COMPLAINT_REGISTRATION_PENDING);assertThat(claim.getNextFollowUpDate()).isEqualTo(today.plusDays(1));verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_COMPLAINT_REGISTRATION_PENDING),anyString(),anyString(),anyMap());unchangedTicket();}
 @Test void complaintPendingRequiresMinimumDetails(){claim.setManufacturerName(null);assertThatThrownBy(()->service.markComplaintPending(1L,2L,new MarkComplaintRegistrationPendingRequest(today,WarrantyContactMethod.PHONE,"Called",today,0L),"ADMIN")).hasMessageContaining("400");}
 @Test void registerComplaintDefaultsFollowUpFromVisit(){service.registerComplaint(1L,2L,new RegisterWarrantyComplaintRequest("C-1",today,today.plusDays(3),null,0L),"ADMIN");assertThat(claim.getNextFollowUpDate()).isEqualTo(today.plusDays(4));assertThat(claim.getFollowUpSource()).isEqualTo(WarrantyFollowUpSource.EXPECTED_VISIT_DEFAULT);assertThat(claim.getState()).isEqualTo(WarrantyClaimState.VISIT_PENDING);unchangedTicket();}
 @Test void registerComplaintDoesNotRequireSeparateWarrantyOwner(){claim.setWarrantyOwnerEmployeeId(null);service.registerComplaint(1L,2L,new RegisterWarrantyComplaintRequest("C",today,null,today,0L),"ADMIN");assertThat(claim.getManufacturerComplaintNumber()).isEqualTo("C");}
 @Test void registerComplaintRequiresComplaintNumber(){assertThatThrownBy(()->service.registerComplaint(1L,2L,new RegisterWarrantyComplaintRequest(" ",today,null,today,0L),"ADMIN")).hasMessageContaining("complaint number");}
 @Test void scheduleVisitRequiresComplaint(){assertThatThrownBy(()->service.scheduleVisit(1L,2L,new ScheduleWarrantyVisitRequest(today.plusDays(1),null,null,null,null,null,0L),"ADMIN")).hasMessageContaining("409");}
 @Test void expectedVisitUpdatePreservesManualFollowUp(){registered();claim.setExpectedVisitDate(today.plusDays(2));claim.setNextFollowUpDate(today.plusDays(5));claim.setFollowUpSource(WarrantyFollowUpSource.MANUAL);service.updateExpectedVisit(1L,2L,new UpdateExpectedWarrantyVisitRequest(today.plusDays(4),"Engineer delayed",0L),"ADMIN");assertThat(claim.getNextFollowUpDate()).isEqualTo(today.plusDays(5));verify(audit).record(eq(claim),eq(WarrantyClaimEventType.WARRANTY_EXPECTED_VISIT_UPDATED),anyString(),anyString(),anyMap());}
 @Test void completedVisitMovesToAwaitingResultAndKeepsResultPending(){registered();claim.setExpectedVisitDate(today);service.recordVisit(1L,2L,new RecordWarrantyVisitRequest(today,WarrantyVisitOutcome.INSPECTION_COMPLETED,"Inspected",null,null,null,null,0L),"ADMIN");assertThat(claim.getState()).isEqualTo(WarrantyClaimState.VISIT_COMPLETED_AWAITING_RESULT);assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.PENDING);unchangedTicket();}
 @Test void engineerNoShowRemainsOperational(){registered();claim.setExpectedVisitDate(today);service.recordVisit(1L,2L,new RecordWarrantyVisitRequest(today,WarrantyVisitOutcome.ENGINEER_DID_NOT_VISIT,"No show",null,null,null,today.plusDays(1),0L),"ADMIN");assertThat(claim.getState()).isEqualTo(WarrantyClaimState.VISIT_PENDING);assertThat(claim.getResult()).isEqualTo(WarrantyClaimResult.PENDING);}
 @Test void staleActionReturnsConflict(){assertThatThrownBy(()->service.markComplaintPending(1L,2L,new MarkComplaintRegistrationPendingRequest(today,WarrantyContactMethod.PHONE,"Called",today,9L),"ADMIN")).hasMessageContaining("409");}
 @Test void authorizationIsEnforced(){doThrow(new ResponseStatusException(HttpStatus.FORBIDDEN,"Access denied")).when(access).requireAllowed("USER",AccessKey.VIEW_TICKETS);assertThatThrownBy(()->service.markComplaintPending(1L,2L,new MarkComplaintRegistrationPendingRequest(today,WarrantyContactMethod.PHONE,"Called",today,0L),"USER")).hasMessageContaining("403");}
 @Test void auditFailureFailsTheActionTransaction(){doThrow(new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Audit failed")).when(audit).record(any(),eq(WarrantyClaimEventType.WARRANTY_COMPLAINT_REGISTRATION_PENDING),anyString(),anyString(),anyMap());assertThatThrownBy(()->service.markComplaintPending(1L,2L,new MarkComplaintRegistrationPendingRequest(today,WarrantyContactMethod.PHONE,"Called",today,0L),"ADMIN")).hasMessageContaining("500");}
 private void registered(){claim.setManufacturerComplaintNumber("C1");claim.setComplaintRegisteredDate(today);}private void unchangedTicket(){assertThat(ticket.getStatus()).isEqualTo(TicketStatus.IN_PROGRESS);assertThat(ticket.getPickedByEmployeeId()).isEqualTo("TECH");}
}
