name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Restart Backend
        run: |
          cd ~/apps/KEBackend
          git pull
          chmod +x gradlew
          ./gradlew clean build -x test
          sudo systemctl restart backend
